name: Runner

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Test
        uses: borales/actions-yarn@v4
        with:
          cmd: jest

      - name: Run Start
        uses: borales/actions-yarn@v4
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          cmd: start
