name: Runner

on:
  push
  # schedule:
  #   - cron: "0 0 * * *" #run every at 00:00:00s UTC / 08.00 GMT +7 / 09.00 GMT +8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Test
        uses: borales/actions-yarn@v4
        with:
          cmd: jest

      - name: Run Start
        uses: borales/actions-yarn@v4
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{TELEGRAM_BOT_TOKEN}}
          TELEGRAM_BOT_CHAT_ID: ${{TELEGRAM_BOT_CHAT_ID}}
        with:
          cmd: start
